// Where a book's RENDERED PAGES live — ported from app/data/audioPages.ts.
//
// The audio is per VOICE; the paper is per BOOK. A PDF does not change when a
// second narrator reads it, so pages/<slug>/v1/ is published once and every
// pressing points at the same leaves.
//
// ABSENT IS A REAL STATE, not an error: a book with no rendered pages falls
// back to the reflowed galley. Most of the shelf will be in that state for a
// long time, so every path here answers "no" cheaply and never throws.
//
// asBookPages() is the gate everything off the wire goes through — a
// half-written manifest must degrade to the galley, never paint a book with
// holes in it.

import { audioUrl } from "./audioResolve";

/**
 * One run of characters, printed once, on one page.
 *
 *   [paraIdx, charStart, charEnd, pageN, x, y, w, h]
 *
 * charStart/charEnd index the SAME paragraph strings the galley uses, which is
 * what lets a word's timing (galley) and a word's position (here) meet without
 * either file knowing about the other. x/y/w/h are NORMALISED 0..1 against
 * pageW/pageH, origin top-left — so a client scales them to whatever size it
 * happens to be rendering the page at.
 */
export type PageBox = [number, number, number, number, number, number, number, number];

export type BookPages = {
  v: number;
  slug: string;
  pageW: number;
  pageH: number;
  pages: { n: number; image: string }[];
  chapters: { idx: number; firstPage: number; lastPage: number; boxes: PageBox[] }[];
};

/** The committed pointer, mirrored from audioEditions.json. */
type PagesRecord = { v: number; n: number; w: number; h: number; manifest: string };

// Only The Little Prince is rendered so far. Regenerated by
// scripts/gen-mobile-shelf.mjs when that changes.
const PAGES: Record<string, PagesRecord> = {
  "the-little-prince": {
    v: 1,
    n: 54,
    w: 1191,
    h: 1684,
    manifest: "pages/the-little-prince/v1/pages.json",
  },
};

/** True when this book has rendered pages to read from. */
export const hasPages = (slug: string): boolean => !!PAGES[slug];

/**
 * What the pointer claims about the shape of the book WITHOUT fetching: page
 * count and rendered pixel size. Enough to stand a correctly proportioned
 * sheet of paper before a single byte of art has arrived — which is the whole
 * reason the pointer is committed rather than derived.
 */
export const pagesShape = (slug: string): { n: number; w: number; h: number } | null => {
  const p = PAGES[slug];
  return p ? { n: p.n, w: p.w, h: p.h } : null;
};

const dirFor = (slug: string): string => {
  const path = PAGES[slug]?.manifest ?? "";
  const cut = path.lastIndexOf("/");
  return cut < 0 ? "" : path.slice(0, cut + 1);
};

/** Reject anything that would paint a book with holes in it. */
function asBookPages(raw: unknown, slug: string): BookPages | null {
  const m = raw as Partial<BookPages> | null;
  if (!m || typeof m !== "object") return null;
  if (!Array.isArray(m.pages) || !m.pages.length) return null;
  if (!Array.isArray(m.chapters)) return null;
  if (!(m.pageW! > 0) || !(m.pageH! > 0)) return null;
  if (m.pages.some((p) => typeof p?.image !== "string" || !(p.n >= 0))) return null;
  return { ...(m as BookPages), slug };
}

const cache = new Map<string, BookPages | null>();

/** Fetch and validate a book's page manifest. Null means "read the galley". */
export async function loadPages(slug: string): Promise<BookPages | null> {
  if (cache.has(slug)) return cache.get(slug)!;
  const path = PAGES[slug]?.manifest;
  if (!path) {
    cache.set(slug, null);
    return null;
  }
  try {
    const res = await fetch(audioUrl(path));
    if (!res.ok) throw new Error(String(res.status));
    const man = asBookPages(await res.json(), slug);
    cache.set(slug, man);
    return man;
  } catch {
    cache.set(slug, null);
    return null;
  }
}

/** The absolute URL of one rendered page. */
export const pageImageUrl = (slug: string, image: string): string =>
  audioUrl(dirFor(slug) + image);

/** Leaf index (0-based, into `pages`) for a printed page number. */
export function leafOfPage(man: BookPages, pageN: number): number {
  const i = man.pages.findIndex((p) => p.n === pageN);
  return i < 0 ? 0 : i;
}

/** The first leaf of a chapter — where the needle drops a reader. */
export function leafOfChapter(man: BookPages, chapter: number): number {
  const ch = man.chapters.find((c) => c.idx === chapter);
  return ch ? leafOfPage(man, ch.firstPage) : 0;
}
