// The Night Scriptorium palette, lifted from the site's app/data/theme.ts.
//
// The web theme rewrites ~150 colour literals into CSS custom properties. Most
// of those are long-tail parchment tints (`x-<hex>`) generated by scanning the
// page builders — they exist because the HTML was authored with hardcoded
// colours, not because the design has 150 colours. The app has no such legacy,
// so it ships only the NAMED brand roles below. If a screen needs a tint that
// isn't here, it is almost certainly reaching for one of these.
//
// Keep the two columns in step with theme.ts. Light is the source of truth;
// dark is the navy Night Scriptorium — never brown, never a brown-tinted dark.

export type Mode = "light" | "dark";

type Pair = readonly [light: string, dark: string];

const PALETTE = {
  /* surfaces */
  paper: ["#faf7ef", "#0d1322"],
  hero: ["#fcfaf4", "#0a0f1c"],
  white: ["#ffffff", "#141b2e"],
  navpaper: ["#f7f1e2", "#192236"],
  cream1: ["#f4ebdd", "#171f33"],
  cream2: ["#fbf6ea", "#1a2338"],
  cream3: ["#efe2cc", "#161e31"],
  cream4: ["#fbf9f2", "#1b2439"],
  cream5: ["#fdfaf0", "#1d263c"],
  /** The field surface — .rr-pf-in's #FFFDF6 sits in this token's band. */
  cream6: ["#fffdf2", "#1e283f"],
  /* the tear reveal sits brighter than its neighbours so the deckle still
     reads as a cutout at night */
  tear: ["#f6efdf", "#26314e"],
  drawer1: ["#f2e7cc", "#1e2740"],
  drawer2: ["#ebdcba", "#1a2237"],
  drawer3: ["#e6d4ac", "#151d30"],

  /* ink */
  ink: ["#0b0a08", "#f2e9d8"],
  ink2: ["#171411", "#e8decb"],
  inkwarm: ["#30271d", "#e3d7c0"],
  inkhover: ["#2a231c", "#e5d9c2"],

  /* metal + earth */
  brown: ["#6e563a", "#c4a37a"],
  brass: ["#9b7a4d", "#c9a662"],
  gold2: ["#8c6a3f", "#c19a5e"],
  gold4: ["#795b38", "#bd9868"],
  rrgold: ["#9b7540", "#c9a662"],

  /* red ink — as TEXT it brightens at night. As cloth it does not: see
     OBJECT below, which is the app's equivalent of theme.ts's ISLAND_ROOTS. */
  brick: ["#7e2d1f", "#d98a70"],
  brick2: ["#6d2922", "#b96a52"],
} as const satisfies Record<string, Pair>;

export type ColorName = keyof typeof PALETTE;
export type Colors = Record<ColorName, string>;

const LIGHT = Object.fromEntries(
  Object.entries(PALETTE).map(([k, v]) => [k, v[0]]),
) as Colors;

const DARK = Object.fromEntries(
  Object.entries(PALETTE).map(([k, v]) => [k, v[1]]),
) as Colors;

export function colorsFor(mode: Mode): Colors {
  return mode === "dark" ? DARK : LIGHT;
}

/**
 * Object colours — the app's ISLAND_ROOTS.
 *
 * On the web, some subtrees keep their light-mode appearance at night because
 * they are *things* rather than surfaces: the library card, cover art, record
 * labels, oxblood cloth. A red cloth binding does not turn pale because the sun
 * went down. These never take the mode, so they are plain constants.
 */
export const OBJECT = {
  oxblood: "#4a1717",
  cloth: "#7e2d1f",
  clothInk: "#f7f1e2",
  cardPaper: "#fdfaf0",
  cardPaperEdge: "#f7f1e2",
} as const;

/** The parchment sheet: a two-stop warm gradient, exactly the sidebar's. */
export const PAPER_GRADIENT = {
  light: ["#fbf9f2", "#f7f1e2"] as const,
  dark: ["#1b2439", "#192236"] as const,
};

/** Hairlines. The portal rules everything with dashes and dots, never solids. */
export const LINE = {
  dashed: { light: "rgba(122,84,44,.42)", dark: "rgba(201,166,98,.34)" },
  dotted: { light: "rgba(11,10,8,.30)", dark: "rgba(242,233,216,.26)" },
  numeral: { light: "rgba(126,45,31,.40)", dark: "rgba(217,138,112,.40)" },
} as const;

export const STATUS_BAR_BG = { light: "#faf7ef", dark: "#0d1322" } as const;
